import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SWRConfig } from "swr"
import { FacultyProvider } from "@/context/FacultyContext";
import { getFaculties } from "@/lib/getFaculties";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const faculties = await getFaculties()

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SWRConfig
          value={{
            keepPreviousData: true,
            revalidateOnMount: false,
            refreshInterval: 1000 * 60 * 5,
            dedupingInterval: 1000 * 60 * 5,
            revalidateOnFocus: false,
            revalidateOnReconnect: false,
          }}
        >
          <FacultyProvider initialFaculties={faculties}>
            {children}
          </FacultyProvider>
        </SWRConfig>
      </body>
    </html>
  );
}
